### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cloojure**
Correct spacing on routes with guards.

### CODE REVIEW

**Comment by SevereOverfl0w** [comment]
Shouldn't /zip be less indented than that?

**Comment by cloojure** [comment]
so the zip map is aligned with the :get map

**Comment by cloojure** [comment]
Hi - I wasn't sure, so I pasted it into IntelliJ/Cursive, and that is the
result..

Basically, the map with with `:request-method` is a key on the same level
as the string  "blog".  So you get

{"blog"  <val-get>
 <req-method-map>
         <zip-handler-map>}

and it aligns both the 2 keys and the 2 values in the map.

**Comment by SevereOverfl0w** [comment]
I've aligned it to what I think makes sense, I suspect cursive is trying to align the nested forms.

**Pull request closed without merging**
